 const chatquestions = [
  "How do I improve my skills in this specific field?",
  "What tools should I learn first for this entire field?",
  "How do I stay updated with trends in this field?",
  "Which skills are most important to grow in this field?",
  "How do I start a successful career in this field?",
  "What common mistakes do beginners make in this field?",
  "How do I choose the right path in this field?",
  "What resources can help me learn this field faster?",
  "How do I know which techniques matter in this field?",
  "What problems do professionals usually face in this field?",
  "How do I know if I am improving in this field?",
  "Which concepts should I master to progress in this field?",
  "How do I build a strong foundation in this field?",
  "What challenges should I expect while entering this field?",
  "How do I practice effectively to grow in this field?",
  "Which habits help people succeed in this entire field?",
  "How do I measure my growth inside this chosen field?",
  "Which books are recommended for beginners in this field?",
  "How do I build confidence while learning this field?",
  "What projects should I try when learning this field?",
  "How do I avoid burnout while working in this field?",
  "Which experts should I follow to understand this field?",
  "How do I find mentors for growth in this field?",
  "What career options exist for people in this field?",
  "How do I switch from another field into this one?",
  "Which mistakes slow down learning in this specific field?",
  "How do I build a portfolio related to this field?",
  "What soft skills are important to grow in this field?",
  "How do I track improvement when learning this field?",
  "What is the most efficient learning method for this field?",
  "How do I understand advanced topics in this field?",
  "Which online courses are best for mastering this field?",
  "How do I get real experience inside this field?",
  "Which tools improve productivity while working in this field?",
  "How do I solve common problems faced in this field?",
  "Which technologies are becoming important in this field?",
  "How do I prepare for interviews in this field?",
  "What does a typical day look like in this field?",
  "How do I build long-term success inside this field?",
  "What strategies help with fast learning in this field?",
  "How do I know if this field suits my personality?",
  "Which areas inside this field pay the highest salaries?",
  "How do I balance theory and practice in this field?",
  "What steps should I take before entering this field?",
  "How do I build connections with people in this field?",
  "Which platforms are best for showcasing skills in this field?",
  "How do I analyze trends happening inside this field?",
  "What are the biggest opportunities currently in this field?",
  "How do I stay motivated while learning this field?"
];


export default chatquestions